<a href="https://colab.research.google.com/github/GAYATHRI-2002/100DaysOfCode/blob/master/Pandas_series_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas series method for dataAnalysis

In [2]:
import pandas as pd
import numpy as np

In [21]:
import pandas as pd

# Dictionary containing states/regions and their corresponding values
avg_temp_data = {
    'Kerala': 28,
    'Andhra Pradesh': 28,
    'Tamil Nadu': 31,
    'Karnataka': 28,
    'Delhi': 38,
    'Maharashtra': 33,
    'Rajasthan': 42,
    'Gujarat': 36,
    'Punjab': 35,
    'West Bengal': 32
}



# Creating the Pandas Series from the dictionary
# series_data = pd.Series(data)

# print(series_data)_read = [2,7,4,9]
# s1 = pd.Series(book_read)

In [22]:
temp_series = pd.Series(avg_temp_data)
temp_series

Kerala            28
Andhra Pradesh    28
Tamil Nadu        31
Karnataka         28
Delhi             38
Maharashtra       33
Rajasthan         42
Gujarat           36
Punjab            35
West Bengal       32
dtype: int64

In [23]:
print(temp_series.head())

Kerala            28
Andhra Pradesh    28
Tamil Nadu        31
Karnataka         28
Delhi             38
dtype: int64

In [24]:
print(temp_series.tail(4))

Rajasthan      42
Gujarat        36
Punjab         35
West Bengal    32
dtype: int64

In [25]:
print(temp_series.describe())

count    10.000000
mean     33.100000
std       4.701064
min      28.000000
25%      28.750000
50%      32.500000
75%      35.750000
max      42.000000
dtype: float64

In [26]:
print(temp_series.value_counts())

28    3
31    1
38    1
33    1
42    1
36    1
35    1
32    1
Name: count, dtype: int64

In [27]:
print(temp_series.unique())

[28 31 38 33 42 36 35 32]

In [28]:
print(temp_series.nunique())

8

In [29]:
print(temp_series.sort_values())

Kerala            28
Andhra Pradesh    28
Karnataka         28
Tamil Nadu        31
West Bengal       32
Maharashtra       33
Punjab            35
Gujarat           36
Delhi             38
Rajasthan         42
dtype: int64

In [30]:
print(temp_series.sort_index())

Andhra Pradesh    28
Delhi             38
Gujarat           36
Karnataka         28
Kerala            28
Maharashtra       33
Punjab            35
Rajasthan         42
Tamil Nadu        31
West Bengal       32
dtype: int64

In [36]:
# Creating a Series with a custom order and an extra state not in the original dictionary
states_list = ['Andhra Pradesh', 'Delhi', 'Tamil Nadu', 'Madhya Pradesh', 'Kerala', 'Karnataka','Rajasthan','Goa']
custom_temp_series = pd.Series(avg_temp_data, index=states_list)

In [37]:
custom_temp_series

Andhra Pradesh    28.0
Delhi             38.0
Tamil Nadu        31.0
Madhya Pradesh     NaN
Kerala            28.0
Karnataka         28.0
Rajasthan         42.0
Goa                NaN
dtype: float64

In [38]:
print(custom_temp_series.isna())

Andhra Pradesh    False
Delhi             False
Tamil Nadu        False
Madhya Pradesh     True
Kerala            False
Karnataka         False
Rajasthan         False
Goa                True
dtype: bool

In [39]:
print(custom_temp_series[custom_temp_series.isna()])

Madhya Pradesh   NaN
Goa              NaN
dtype: float64

In [40]:
print(custom_temp_series.notna())

Andhra Pradesh     True
Delhi              True
Tamil Nadu         True
Madhya Pradesh    False
Kerala             True
Karnataka          True
Rajasthan          True
Goa               False
dtype: bool