<a href="https://colab.research.google.com/github/GAYATHRI-2002/100DaysOfCode/blob/master/Pandas_series_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas series method for dataAnalysis

In [1]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

# Dictionary containing states/regions and their corresponding values
avg_temp_data = {
    'Kerala': 28,
    'Andhra Pradesh': 28,
    'Tamil Nadu': 31,
    'Karnataka': 28,
    'Delhi': 38,
    'Maharashtra': 33,
    'Rajasthan': 42,
    'Gujarat': 36,
    'Punjab': 35,
    'West Bengal': 32
}



# Creating the Pandas Series from the dictionary
# series_data = pd.Series(data)

# print(series_data)_read = [2,7,4,9]
# s1 = pd.Series(book_read)

In [ ]:
temp_series = pd.Series(avg_temp_data)
temp_series

Kerala            28
Andhra Pradesh    28
Tamil Nadu        31
Karnataka         28
Delhi             38
Maharashtra       33
Rajasthan         42
Gujarat           36
Punjab            35
West Bengal       32
dtype: int64

In [ ]:
print(temp_series.head())

Kerala            28
Andhra Pradesh    28
Tamil Nadu        31
Karnataka         28
Delhi             38
dtype: int64

In [ ]:
print(temp_series.tail(4))

Rajasthan      42
Gujarat        36
Punjab         35
West Bengal    32
dtype: int64

In [ ]:
print(temp_series.describe())

count    10.000000
mean     33.100000
std       4.701064
min      28.000000
25%      28.750000
50%      32.500000
75%      35.750000
max      42.000000
dtype: float64

In [ ]:
print(temp_series.value_counts())

28    3
31    1
38    1
33    1
42    1
36    1
35    1
32    1
Name: count, dtype: int64

In [ ]:
print(temp_series.unique())

[28 31 38 33 42 36 35 32]

In [ ]:
print(temp_series.nunique())

8

In [ ]:
print(temp_series.sort_values())

Kerala            28
Andhra Pradesh    28
Karnataka         28
Tamil Nadu        31
West Bengal       32
Maharashtra       33
Punjab            35
Gujarat           36
Delhi             38
Rajasthan         42
dtype: int64

In [ ]:
print(temp_series.sort_index())

Andhra Pradesh    28
Delhi             38
Gujarat           36
Karnataka         28
Kerala            28
Maharashtra       33
Punjab            35
Rajasthan         42
Tamil Nadu        31
West Bengal       32
dtype: int64

In [ ]:
# Creating a Series with a custom order and an extra state not in the original dictionary
states_list = ['Andhra Pradesh', 'Delhi', 'Tamil Nadu', 'Madhya Pradesh', 'Kerala', 'Karnataka','Rajasthan','Goa']
custom_temp_series = pd.Series(avg_temp_data, index=states_list)

In [ ]:
custom_temp_series

Andhra Pradesh    28.0
Delhi             38.0
Tamil Nadu        31.0
Madhya Pradesh     NaN
Kerala            28.0
Karnataka         28.0
Rajasthan         42.0
Goa                NaN
dtype: float64

In [ ]:
print(custom_temp_series.isna())

Andhra Pradesh    False
Delhi             False
Tamil Nadu        False
Madhya Pradesh     True
Kerala            False
Karnataka         False
Rajasthan         False
Goa                True
dtype: bool

In [ ]:
print(custom_temp_series[custom_temp_series.isna()])

Madhya Pradesh   NaN
Goa              NaN
dtype: float64

In [ ]:
print(custom_temp_series.notna())

Andhra Pradesh     True
Delhi              True
Tamil Nadu         True
Madhya Pradesh    False
Kerala             True
Karnataka          True
Rajasthan          True
Goa               False
dtype: bool

In [2]:
data_dict = {
    "Product": ["Laptop", "Smartphone", "Tablet", "Headphones"],
    "Price": [75000, 45000, 25000, 3000],
    "In_Stock": [True, True, False, True]
}

In [3]:
df = pd.DataFrame(data_dict)

In [4]:
df

      Product  Price  In_Stock
0      Laptop  75000      True
1  Smartphone  45000      True
2      Tablet  25000     False
3  Headphones   3000      True

In [5]:
employee_data = [
    ["John", 28, "Marketing"],
    ["Anna", 35, "Finance"],
    ["mike", 40, "IT"]
]

In [6]:
df_list = pd.DataFrame(employee_data, columns=["Name", "Age", "Department"])

In [7]:
df_list

   Name  Age Department
0  John   28  Marketing
1  Anna   35    Finance
2  mike   40         IT

In [8]:
city_data = [
    {"City": "Kochi", "Population": 2110000},
    {"City": "Bengaluru", "Population": 8440000},
    {"City": "Mumbai", "Population": 12400000}
]

In [9]:
df_list_dict = pd.DataFrame(city_data)

In [10]:
df_list_dict

        City  Population
0      Kochi     2110000
1  Bengaluru     8440000
2     Mumbai    12400000

In [11]:
df.head(4)

      Product  Price  In_Stock
0      Laptop  75000      True
1  Smartphone  45000      True
2      Tablet  25000     False
3  Headphones   3000      True

In [12]:
df.tail()

      Product  Price  In_Stock
0      Laptop  75000      True
1  Smartphone  45000      True
2      Tablet  25000     False
3  Headphones   3000      True

In [13]:
df['Product']

0        Laptop
1    Smartphone
2        Tablet
3    Headphones
Name: Product, dtype: object

In [15]:
df[['Product','Price']]

      Product  Price
0      Laptop  75000
1  Smartphone  45000
2      Tablet  25000
3  Headphones   3000

In [16]:
df['shoplocation'] = 'kochi'
print(df)

      Product  Price  In_Stock shoplocation
0      Laptop  75000      True        kochi
1  Smartphone  45000      True        kochi
2      Tablet  25000     False        kochi
3  Headphones   3000      True        kochi

In [17]:
df['Price_with_GST'] = df['Price'] * 1.3
print(df)

      Product  Price  In_Stock shoplocation  Price_with_GST
0      Laptop  75000      True        kochi         97500.0
1  Smartphone  45000      True        kochi         58500.0
2      Tablet  25000     False        kochi         32500.0
3  Headphones   3000      True        kochi          3900.0